feat: add index to collections
witnet/data-feeds-explorer pull request #109
Opened 2021-12-02 16:09 UTC by gabaldon

2021-12-02 17:32 UTC, Tommytrg commented
@aesedepece , as our mongodb guru, do you think we should add any other index to improve the performance?

2021-12-02 17:47 UTC, Tommytrg requested changes

2021-12-02 17:47 UTC, Tommytrg commented on packages/api/src/repository/ResultRequest.ts
> +    this.collection.createIndex({ feedFullName: 1 })
In ResultRequest we are looking also for ` timestamp: { $gt: timestamp.toString() }` so the index should include it:

```suggestion
    this.collection.createIndex({ feedFullName: 1, timestamp: -1 })
```

2021-12-09 08:55 UTC, aesedepece approved these changes

2021-12-09 12:15 UTC, merged