Chore(api): Add Conflux eSpace price feeds
witnet/data-feeds-explorer pull request #170
Opened 2022-04-05 10:20 UTC by guidiaz

Close https://github.com/witnet/witnet-solidity-bridge/issues/233.

2022-04-05 16:51 UTC, Tommytrg approved these changes

2022-04-06 09:23 UTC, gabaldon approved these changes

2022-04-06 09:24 UTC, gabaldon requested changes

2022-04-06 09:24 UTC, gabaldon commented on packages/api/src/dataFeedsRouter.json
> +          "name": "Conflux eSpace Testnet",
```suggestion
          "name": "Conflux eSpace (Testnet)",
```

2022-04-06 09:35 UTC, merged

2022-04-07 11:10 UTC, aesedepece commented on packages/api/src/dataFeedsRouter.json
> +          "blockExplorer": "https://evmtestnet.confluxscan.net/address//{address}?tab=contract-viewer",
Hey there's a double slash `//` here. Please fix!

2022-04-07 11:38 UTC, guidiaz commented on packages/api/src/dataFeedsRouter.json
> +          "blockExplorer": "https://evmtestnet.confluxscan.net/address//{address}?tab=contract-viewer",
See on https://github.com/witnet/data-feeds-explorer/pull/173.