feat(api): add eth/usd on arbitrum goerli
witnet/data-feeds-explorer pull request #271
Opened 2022-11-09 18:47 UTC by guidiaz

2022-11-10 14:38 UTC, Tommytrg requested changes

2022-11-10 14:38 UTC, Tommytrg commented on packages/api/migrations/1_rename-boba-networks.js
> +    }
I had to do some small changes to make it work:

```suggestion
    const resultRequestCollection = db.collection('result_request')

    const promises = (
      await resultRequestCollection
        .find({
          feedFullName: /boba-/
        })
        .toArray()
    )
      .map(resultRequest => ({
        ...resultRequest,
        feedFullName: resultRequest.feedFullName.replace(
          /boba-/,
          'boba-ethereum-'
        )
      }))
      .map(resultRequest =>
        resultRequestCollection.updateOne(
          { _id: resultRequest._id },
          { $set: { feedFullName: resultRequest.feedFullName } }
        )
      )

    await Promise.all(promises)
```

2022-11-10 14:38 UTC, Tommytrg commented on packages/api/migrations/2_rename-conflux-networks.js
> +        )
```suggestion
  const resultRequestCollection = db.collection('result_request')
    const updateConfluxTethysPromises = (
      await resultRequestCollection
        .find({
          feedFullName: /conflux-tethys/
        })
        .toArray()
    )
      .map(resultRequest => ({
        ...resultRequest,
        feedFullName: resultRequest.feedFullName.replace(
          /conflux-tethys/,
          'conflux-core-mainnet'
        )
      }))
      .map(resultRequest =>
        resultRequestCollection.updateOne(
          { _id: resultRequest._id },
          { $set: { feedFullName: resultRequest.feedFullName } }
        )
      )

    const updateConfluxRinkebyPromises = (
      await resultRequestCollection.find({
        feedFullName: /conflux-rinkeby/
      })
    )
      .map(resultRequest => ({
        ...resultRequest,
        feedFullName: resultRequest.feedFullName.replace(
          /conflux-rinkeby/,
          'conflux-core-rinkeby'
        )
      }))
      .map(resultRequest =>
        resultRequestCollection.updateOne(
          { _id: resultRequest._id },
          { $set: { feedFullName: resultRequest.feedFullName } }
        )
      )

    await Promise.all(
      [updateConfluxTethysPromises, updateConfluxRinkebyPromises].flat()
    )
  }
```

2022-11-11 11:09 UTC, gabaldon approved these changes

2022-11-11 11:11 UTC, merged