Feat/elastos.testnet
witnet/data-feeds-explorer pull request #306
Opened 2023-03-28 15:46 UTC by guidiaz

2023-03-28 15:54 UTC, gabaldon commented on packages/api/src/dataFeedsRouter.json
> +              "label": "$",
```suggestion
              "label": "₮",
```

2023-03-28 19:11 UTC, aesedepece requested changes

2023-03-28 19:11 UTC, aesedepece commented on packages/api/src/dataFeedsRouter.json
> +              "label": "$",
:+1:

2023-03-29 06:52 UTC, gabaldon approved these changes

2023-03-29 07:15 UTC, merged